### ISSUE TITLE
Defaults app window size

### ISSUE THREAD

**Issue by jiachen247** [AY1920S2-CS2103T-W16-2/main#70]
I'm currently using the defaults by address book! Anybody has any suggestions or issues with this! This greatly affects the look and feel of our product!

```
    private static final double DEFAULT_HEIGHT = 600;
    private static final double DEFAULT_WIDTH = 740;
```

**Comment by chishanw** [comment]
@alloystory if you've pushed the code for auto resizing of the window, we can close this!

Update: Fixed this issue, closing now!
